// FAKE PLANT DATA FOR APP WITH EXISTING PLANTS
const plants = [
  {
    id: 1,
    name: "ZZ Plant",
    nickname: "Zillian Murphy",
    light: ["low"],
    watering: [1, 'weekly'],
    humidity: "moderate",
    photoURL: "https://www.scentandviolet.com/files/6515/9675/8096/zz-plant-scentandviolet-houston-tx.jpg",
    categories: ['chill-af', 'indoor'],
    lastWatered: '2021-01-01',
  },
  {
    id: 2,
    name: "Rubber Tree",
    nickname: null,
    light: ["medium", "inderect"],
    watering: [1, 'weekly'],
    humidity: "moderate",
    photoURL: "https://www.gardeningknowhow.com/wp-content/uploads/2008/05/rubber-plant.jpg",
    categories: ['chill-af'],
    lastWatered: '2021-01-01',
  },
  {
    id: 3,
    name: "Parallel Peperomia",
    nickname: "Pepperoni",
    light: ["medium", "inderect"],
    watering: [1, 'weekly'],
    humidity: "moderate",
    photoURL: "https://www.gardentags.com/profile/heatherdirtyhands/images/1382336/750/peperomia-puteolata.jpeg",
    categories: ['high-maintenance'],
    lastWatered: '2021-01-01',
  },
  {
    id: 4,
    name: "Christmas Cactus",
    nickname: null,
    light: ["medium", "bright"],
    watering: [1, 'bi-weekly'],
    humidity: "low",
    photoURL: "https://www.gardeningknowhow.com/wp-content/uploads/2020/11/christmas-cactus-1.jpg",
    categories: ['chill-af', 'flowering', 'outdoor'],
    lastWatered: '2021-01-01',
  },
  {
    id: 5,
    name: "Golden Pothos",
    nickname: null,
    light: ["medium", "inderect"],
    watering: [1, 'weekly'],
    humidity: "moderate",
    photoURL: "https://cdn.shopify.com/s/files/1/0584/6065/products/7617942d96a9d4d574ff35bceb1d6260f1b0165b_800x.jpg?v=1585171081",
    categories: ['chill-af', 'indoor'],
    lastWatered: '2021-01-01',
  },
  {
    id: 6,
    name: "Alocasia Polly",
    nickname: null,
    light: ["low", "inderect"],
    watering: [1, 'weekly'],
    humidity: "high",
    photoURL: "https://www.dutchnurseries.co.uk/upload/mt/dn204/products/lg_20174115-1.-green-house-plant.jpg",
    categories: ['high-maintenance', 'indoor'],
    lastWatered: '2021-01-01',
  },
  {
    id: 7,
    name: "Goldfish Plant",
    nickname: "Goldilock",
    light: ["medium", "inderect"],
    watering: [1, 'weekly'],
    humidity: "moderate",
    photoURL: "https://i.pinimg.com/originals/31/73/7c/31737c64130ec32aecc1346c0a2e16c2.jpg",
    categories: ['flowering', 'indoor'],
    lastWatered: '2021-01-01',
  },
  {
    id: 8,
    name: "Snake Plant",
    nickname: "Snake Daddy",
    light: ["low"],
    watering: [1, 'monthly'],
    humidity: "moderate",
    photoURL: "https://res.cloudinary.com/dpbieru1u/image/upload/v1609648834/planterimages/hu26sbhrf5er1a0xjycl.jpg",
    categories: ['chill-af', 'indoor'],
    lastWatered: '2021-01-01',
  },
  {
    id: 9,
    name: "Snake Plant",
    nickname: "Snake Baby",
    light: ["low"],
    watering: [1, 'monthly'],
    humidity: "moderate",
    photoURL: "https://res.cloudinary.com/dpbieru1u/image/upload/v1609788979/planterimages/IMG_9960_izg2iz.jpg",
    categories: ['chill-af', 'indoor'],
    lastWatered: '2021-01-01',
  },
  {
    id: 10,
    name: "Basil",
    nickname: "Green",
    light: ["moderate"],
    watering: [2, 'weekly'],
    humidity: "moderate",
    photoURL: "https://res.cloudinary.com/dpbieru1u/image/upload/v1609744765/planterimages/qqzizfcfet5bnq1js1cm.jpg",
    categories: ['herb', 'indoor'],
    lastWatered: '2021-01-01',
  },

]

// const plants = [];

module.exports = plants;